version: '3.8'

services:
  whisper:
    build:
      context: ./transcription-service
      dockerfile: Dockerfile
    volumes:
      - ./transcription-service:/app
    ports:
      - "5005:5005"
    environment:
      - FLASK_ENV=development
